version: '3.4'

services:
  go-products-example-ddd:
    container_name: go-products-example-ddd
    image: go-products-example-ddd
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis:6379"
      MYSQL_DSN: "root:123456@tcp(mysql:3306)/godb?charset=utf8mb4&parseTime=True&loc=Local"
      DynamoDBENDPOINTURL: "http://dynamodb:8000"
      DynamoDBID: "dummyID"
      DynamoDBSECRET: "dummySECRET"
      DynamoDBREGION: "us-east-1"
      DynamoDBPROFILE: "localstack"
      JAEGER_HOST: "jaeger:6831"
    links:
      - mysql
    depends_on:
      - mysql
      - redis
      - dynamodb
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
  mysql:
    image: mysql:latest
    container_name: mysqldb
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: godb
      MYSQL_HOST: root
      MYSQL_PORT: 3306
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  jaeger:
    container_name: jaeger-container
    restart: always
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  grafana:
    container_name: grafana-container
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    container_name: prometheus-container
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - go-products-example-ddd