version: '3.4'

services:
  go-products-example-ddd:
    container_name: go-products-example-ddd
    image: go-products-example-ddd
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis:6379"
      MYSQL_DSN: "root:123456@tcp(mysql:3306)/godb?charset=utf8mb4&parseTime=True&loc=Local"
      DynamoDBENDPOINTURL: "http://dynamodb:8000"
      DynamoDBID: "dummyID"
      DynamoDBSECRET: "dummySECRET"
      DynamoDBREGION: "us-east-1"
      DynamoDBPROFILE: "localstack"
    links:
      - mysql
    depends_on:
      - mysql
      - redis
      - dynamodb
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
  mysql:
    image: mysql:latest
    container_name: mysqldb
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: godb
      MYSQL_HOST: root
      MYSQL_PORT: 3306
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal