#global:
#  scrape_interval:     15s
#  evaluation_interval: 15s
#
#scrape_configs:
#  - job_name: go-app
#    scrape_interval: 10s
#    static_configs:
#      - targets:
#          - go-app:9090
#
#
global:
  scrape_interval: 15s # By default, scrape targets every 15seconds. # Attach these labels to any time series or alerts when #communicating with external systems (federation, remote storage, #Alertmanager).
  external_labels:
    monitor: 'monitoring'
# Scraping Prometheus itself
scrape_configs:
  - job_name: 'go-app-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name