apiVersion: v1
kind: Service
metadata:
  name: go-app-jaeger
  labels:
    app: app-jaeger
spec:
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 30103
      name: node-port
    - port: 5775
      name: jaeger-port1
      protocol: UDP
    - port: 6831
      name: jaeger-port2
      protocol: UDP
    - port: 6832
      name: jaeger-port3
      protocol: UDP
    - port: 5778
      name: jaeger-port4
      protocol: TCP
    - port: 9411
      name: jaeger-port5
      protocol: TCP
  selector:
    app: app-jaeger
    tier: jaeger
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pv-claim
  labels:
    app: app-jaeger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-jaeger
  labels:
    app: app-jaeger
spec:
  selector:
    matchLabels:
      app: app-jaeger
      tier: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-jaeger
        tier: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:latest
          name: jaeger
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
              name: jaeger
          volumeMounts:
            - name: jaeger-persistent-storage
              mountPath: /var/lib/jaeger
      volumes:
        - name: jaeger-persistent-storage
          persistentVolumeClaim:
            claimName: jaeger-pv-claim
