// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	redis "github.com/go-redis/redis/v7"
	mock "github.com/stretchr/testify/mock"
)

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

// GetClient provides a mock function with given fields:
func (_m *RedisClient) GetClient() *redis.Client {
	ret := _m.Called()

	var r0 *redis.Client
	if rf, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}

	return r0
}
