// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *AuthHandler) Login(c *gin.Context) {
	_m.Called(c)
}

// Logout provides a mock function with given fields: c
func (_m *AuthHandler) Logout(c *gin.Context) {
	_m.Called(c)
}

// Refresh provides a mock function with given fields: c
func (_m *AuthHandler) Refresh(c *gin.Context) {
	_m.Called(c)
}
