// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	gorm "github.com/jinzhu/gorm"
	mock "github.com/stretchr/testify/mock"
)

// MysqlClient is an autogenerated mock type for the MysqlClient type
type MysqlClient struct {
	mock.Mock
}

// GetClient provides a mock function with given fields:
func (_m *MysqlClient) GetClient() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}
