// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ProductHandler is an autogenerated mock type for the ProductHandler type
type ProductHandler struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: c
func (_m *ProductHandler) AddProduct(c *gin.Context) {
	_m.Called(c)
}

// DeleteProduct provides a mock function with given fields: c
func (_m *ProductHandler) DeleteProduct(c *gin.Context) {
	_m.Called(c)
}

// GetAllProducts provides a mock function with given fields: c
func (_m *ProductHandler) GetAllProducts(c *gin.Context) {
	_m.Called(c)
}

// GetProductByID provides a mock function with given fields: c
func (_m *ProductHandler) GetProductByID(c *gin.Context) {
	_m.Called(c)
}

// UpdateProduct provides a mock function with given fields: c
func (_m *ProductHandler) UpdateProduct(c *gin.Context) {
	_m.Called(c)
}
