// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/berkayersoyy/go-products-example-ddd/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: user
func (_m *UserRepository) AddUser(user domain.User) domain.User {
	ret := _m.Called(user)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(domain.User) domain.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: user
func (_m *UserRepository) DeleteUser(user domain.User) {
	_m.Called(user)
}

// GetAllUsers provides a mock function with given fields:
func (_m *UserRepository) GetAllUsers() []domain.User {
	ret := _m.Called()

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func() []domain.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	return r0
}

// GetUserByID provides a mock function with given fields: id
func (_m *UserRepository) GetUserByID(id uint) domain.User {
	ret := _m.Called(id)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(uint) domain.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	return r0
}

// GetUserByUsername provides a mock function with given fields: username
func (_m *UserRepository) GetUserByUsername(username string) domain.User {
	ret := _m.Called(username)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(string) domain.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	return r0
}
