// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserHandlerDynamoDb is an autogenerated mock type for the UserHandlerDynamoDb type
type UserHandlerDynamoDb struct {
	mock.Mock
}

// Delete provides a mock function with given fields: c
func (_m *UserHandlerDynamoDb) Delete(c *gin.Context) {
	_m.Called(c)
}

// FindByUUID provides a mock function with given fields: c
func (_m *UserHandlerDynamoDb) FindByUUID(c *gin.Context) {
	_m.Called(c)
}

// FindByUsername provides a mock function with given fields: c
func (_m *UserHandlerDynamoDb) FindByUsername(c *gin.Context) {
	_m.Called(c)
}

// Insert provides a mock function with given fields: c
func (_m *UserHandlerDynamoDb) Insert(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *UserHandlerDynamoDb) Update(c *gin.Context) {
	_m.Called(c)
}
